<a href="https://colab.research.google.com/github/adibansal06/UCS420_CC_LabAssignments_1024170054/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = [
    {'Tid' : 1,'Refund' : 'Yes', 'Marital Status' : 'Single', 'Taxable Income' : '125K', 'Cheat' : 'No'},
    {'Tid' : 2,'Refund' : 'No', 'Marital Status' : 'Married', 'Taxable Income' : '100K', 'Cheat' : 'No'},
    {'Tid' : 3,'Refund' : 'No', 'Marital Status' : 'Single', 'Taxable Income' : '70K', 'Cheat' : 'No'},
    {'Tid' : 4,'Refund' : 'Yes', 'Marital Status' : 'Married', 'Taxable Income' : '120K', 'Cheat' : 'No'},
    {'Tid' : 5,'Refund' : 'No', 'Marital Status' : 'Divorced', 'Taxable Income' : '95K', 'Cheat' : 'Yes'},
    {'Tid' : 6,'Refund' : 'No', 'Marital Status' : 'Married', 'Taxable Income' : '60K', 'Cheat' : 'No'},
    {'Tid' : 7,'Refund' : 'Yes', 'Marital Status' : 'Divorced', 'Taxable Income' : '220K', 'Cheat' : 'No'},
    {'Tid' : 8,'Refund' : 'No', 'Marital Status' : 'Single', 'Taxable Income' : '85K', 'Cheat' : 'Yes'},
    {'Tid' : 9,'Refund' : 'No', 'Marital Status' : 'Married', 'Taxable Income' : '75K', 'Cheat' : 'No'},
    {'Tid' : 10,'Refund' : 'No', 'Marital Status' : 'Single', 'Taxable Income' : '90K', 'Cheat' : 'Yes'}
]
df = pd.DataFrame(data)
print(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [5]:
selected_rows = df.iloc[[0,4,7,8]]
print(selected_rows)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [6]:
select1 = df.iloc[3:8]
print(select1)

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [8]:
select2 = df.iloc[4:9, 2:5]
print(select2)

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

In [12]:
select3 = df.iloc[0: , 1:4]
print(select3)

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [24]:
df1 = pd.read_csv('Iris.csv')
print(df1.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [25]:
df1 = df1.drop(3, axis = 0)
print(df1.head(10))

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa

In [26]:
df1 = df1.drop('SepalWidthCm', axis = 1)
print(df1.head(10))

    Id  SepalLengthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1            1.4           0.2  Iris-setosa
1    2            4.9            1.4           0.2  Iris-setosa
2    3            4.7            1.3           0.2  Iris-setosa
4    5            5.0            1.4           0.2  Iris-setosa
5    6            5.4            1.7           0.4  Iris-setosa
6    7            4.6            1.4           0.3  Iris-setosa
7    8            5.0            1.5           0.2  Iris-setosa
8    9            4.4            1.4           0.2  Iris-setosa
9   10            4.9            1.5           0.1  Iris-setosa
10  11            5.4            1.5           0.2  Iris-setosa

In [31]:
data1 = [
    {'Employee_ID' : 101, 'Name' : 'Alice', 'Department' : 'HR', 'Age' : 29, 'Salary' : 50000, 'Years_of_Experience' : 4, 'Joining_Date' : '2020-03-15', 'Gender' : 'Female', 'Bonus' : 5000, 'Rating' : 4.5},
    {'Employee_ID' : 102, 'Name' : 'Bob', 'Department' : 'IT', 'Age' : 34, 'Salary' : 70000, 'Years_of_Experience' : 8, 'Joining_Date' : '2017-07-19', 'Gender' : 'Male', 'Bonus' : 7000, 'Rating' : 4.0},
    {'Employee_ID' : 103, 'Name' : 'Charlie', 'Department' : 'IT', 'Age' : 41, 'Salary' : 65000, 'Years_of_Experience' : 10, 'Joining_Date' : '2013-06-01', 'Gender' : 'Male', 'Bonus' : 6000, 'Rating' : 3.8},
    {'Employee_ID' : 104, 'Name' : 'Diana', 'Department' : 'Marketing', 'Age' : 28, 'Salary' : 000, 'Years_of_Experience' : 3, 'Joining_Date' : '2021-02-10', 'Gender' : 'Female', 'Bonus' : 4500, 'Rating' : 4.7},
    {'Employee_ID' : 105, 'Name' : 'Edward', 'Department' : 'Sales', 'Age' : 38, 'Salary' : 60000, 'Years_of_Experience' : 12, 'Joining_Date' : '2010-11-25', 'Gender' : 'Male', 'Bonus' : 5000, 'Rating' : 3.5}
]
df2 = pd.DataFrame(data1)
print(df2)
df2.to_csv('employees.csv', index = False)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28       0                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [32]:
df2.shape

(5, 10)

In [33]:
df2.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.000000,5.000000,5.0,5.000000
mean,103.000000,34.000000,49000.000000,7.400000,5500.0,4.100000
std,1.581139,5.612486,28372.521918,3.847077,1000.0,0.494975
min,101.000000,28.000000,0.000000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,50000.000000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.000000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.000000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.000000,12.000000,7000.0,4.700000

In [34]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [36]:
df2.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,0,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [37]:
df2.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,0,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [39]:
avg_salary = df2['Salary'].mean()
print(avg_salary)

49000.0

In [40]:
bonus = df2['Bonus'].sum()
print(bonus)

27500

In [42]:
youngest = df2['Age'].min()
print(youngest)

28

In [43]:
high_rating = df2['Rating'].max()
print(high_rating)

4.7

In [45]:
df2 = df2.sort_values(by = 'Salary', ascending=False)
print(df2)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
0          101    Alice         HR   29   50000                    4
3          104    Diana  Marketing   28       0                    3

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
0   2020-03-15  Female   5000     4.5
3   2021-02-10  Female   4500     4.7

In [47]:
conditions = [
    df2['Rating'] >= 4.5,
    (df2['Rating'] >= 4.0) & (df2['Rating'] < 4.0),
    df2['Rating'] < 4.5
]
mark = ['Excellent', 'Good', 'Average']
df2['Performance'] = np.select(conditions, mark, default='Unknown')
print(df2)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
0          101    Alice         HR   29   50000                    4
3          104    Diana  Marketing   28       0                    3

  Joining_Date  Gender  Bonus  Rating Performance
1   2017-07-19    Male   7000     4.0     Average
2   2013-06-01    Male   6000     3.8     Average
4   2010-11-25    Male   5000     3.5     Average
0   2020-03-15  Female   5000     4.5   Excellent
3   2021-02-10  Female   4500     4.7   Excellent

In [48]:
df2.isna()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
0,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False

In [49]:
df2.isnull()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
0,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False

In [52]:
df2 = df2.rename(columns = {'Employee_ID' : 'ID'})
print(df2)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25
0  101    Alice         HR   29   50000                    4   2020-03-15
3  104    Diana  Marketing   28       0                    3   2021-02-10

   Gender  Bonus  Rating Performance
1    Male   7000     4.0     Average
2    Male   6000     3.8     Average
4    Male   5000     3.5     Average
0  Female   5000     4.5   Excellent
3  Female   4500     4.7   Excellent

In [53]:
df2 = df2.rename({'ID' : 'KEY'}, axis=1)
print(df2)

   KEY     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25
0  101    Alice         HR   29   50000                    4   2020-03-15
3  104    Diana  Marketing   28       0                    3   2021-02-10

   Gender  Bonus  Rating Performance
1    Male   7000     4.0     Average
2    Male   6000     3.8     Average
4    Male   5000     3.5     Average
0  Female   5000     4.5   Excellent
3  Female   4500     4.7   Excellent

In [55]:
experienced = df2[df2['Years_of_Experience'] > 5]
print(experienced)

   KEY     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance
1   Male   7000     4.0     Average
2   Male   6000     3.8     Average
4   Male   5000     3.5     Average

In [56]:
IT_people = df2[df2['Department'] == 'IT']
print(IT_people)

   KEY     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance
1   Male   7000     4.0     Average
2   Male   6000     3.8     Average

In [60]:
df2['Tax'] = df2['Salary'] * (90/100)
print(df2)

   KEY     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25
0  101    Alice         HR   29   50000                    4   2020-03-15
3  104    Diana  Marketing   28       0                    3   2021-02-10

   Gender  Bonus  Rating Performance      Tax
1    Male   7000     4.0     Average  63000.0
2    Male   6000     3.8     Average  58500.0
4    Male   5000     3.5     Average  54000.0
0  Female   5000     4.5   Excellent  45000.0
3  Female   4500     4.7   Excellent      0.0

In [62]:
df2.to_csv('ModifiedEmployees.csv', index = False)